name: homebound
description: "Homebound — An AI-Powered After-Hours Public Transport Tracker"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  http: ^1.2.2
  archive: ^3.6.1
  csv: ^6.0.0
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.1
  google_sign_in: ^7.2.0
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
